bibcat:
    build: .
    ports:
        - "5000:5000"
    links:
     - semanticServer
     - search

semanticServer:
    image: jermnelson/semantic-server-core:dev
    ports:
     - "8080:8080"
    volumes:
     - /opt/bibcat_repository/fedora-data:/usr/share/fedora-data
     - /opt/bibcat_triplestore:/usr/share/blazegraph
     - $HOME/local_data:/local_data

search:
    build: .
    dockerfile: DockerfileElasticSearch
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - /opt/bibcat_index:/usr/share/elasticsearch/data

web:
    build: .
    dockerfile: DockerNginx
    links:
     - bibcat:bibcat
    ports:
     -  "80:80"

